[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://swt-labs-api.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[build]
  command = "npm run build"
  publish = "dist" 